/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 逐项返回探测结果——数据库与 Redis 是**真实连接探测**；llm 项只校验**配置就绪性**（不发真实请求：会烧钱，也容易被网络抖动误判，与 probe.py 的口径一致）。任一不可用时整体状态为 down 并返回 503。
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交热点分析任务
         * @description 接受一个或多个热点文本，落库生成 hotspot 与 run 记录，投递异步任务后立即返回。
         *     同一请求内多个热点按顺序分别分析，互不影响。
         */
        post: operations["createAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hotspots/image-clue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 从图片拆解热点线索
         * @description 上传一张热点图片（jpg / png / webp，单张，≤ 10 MB），由多模态模型拆成「热点描述 + 爆点要素」。
         *     图片**只在内存里转成模型输入**——不落盘、不入库；与素材上传是两条独立链路。
         *     解析结果同样不落库：用户确认（可编辑）后随 `POST /api/analyze` 的 `clues` 字段一起提交。
         *     该接口**不要求 ffmpeg**（图片不抽帧）：只要求 `[vision].enabled = true` 与密钥。
         */
        post: operations["createImageClue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询任务状态
         * @description 轮询任务进度；succeeded 后可凭 run_id 取结果，failed 时 error 字段给出失败原因。
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出历史运行
         * @description 按创建时间倒序分页返回历史运行摘要（run_id、状态、热点数与首条热点预览、成本与耗时）。
         */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取运行结果
         * @description 返回该次运行的结构化结果：线索、候选素材、覆盖缺口与文稿。
         */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取报告
         * @description 返回渲染好的报告；html 为自带样式的单文件，md 为可直接复制的文本。
         */
        get: operations["getRunReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}/keyframes/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取素材关键帧图片
         * @description 返回候选素材登记的关键帧图片（JPEG），供结果详情页缩略图使用。
         *     帧路径来自素材库的关键帧缓存目录；素材不存在、下标越界或文件缺失一律 404，
         *     不区分原因（避免暴露素材库内部布局）。
         */
        get: operations["getMaterialKeyframe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出素材库
         * @description 按索引时间倒序分页返回素材库；支持关键词（标题或标签的子串）、类型、打标来源与
         *     主题目录筛选。`dirs` 是**直接子目录**的计数（受 `q` / `type` / `source` 影响、
         *     不受 `dir` 影响），供前端渲染主题导航。磁盘目录是唯一来源，这里是索引副本。
         */
        get: operations["listMaterials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 触发素材库扫描
         * @description 投递一次「增量同步 + 向量回填」：扫描 `<素材根>` 下新增 / 变更 / 消失的文件并落库，
         *     再给缺向量的素材补齐 `embedding`。素材目录不存在时任务以 FAILURE 结束（不做降级）。
         *     进度与失败原因用 `GET /api/materials/tasks/{task_id}` 查。
         */
        post: operations["scanMaterials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传素材
         * @description 流式接收**单个**媒体文件，落到 `<素材根>/<YYYY-MM>/`（同名自动加 `-2` 序号，不覆盖），
         *     随后投递索引任务（抽帧 + 打标 + 向量回填）。
         *     扩展名必须在 `[upload].allowed_extensions` 里（否则 400）；体积上限 `[upload].max_size_gb`
         *     （超限 413，边写边计并清理临时文件）；空文件 400。
         *     文件先写 `.incoming-*.part` 再原子改名，失败不会在素材目录里留下半截文件。
         */
        post: operations["uploadMaterial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询素材索引任务
         * @description 读任务状态：`state` 是 Celery 的标准五态，`step` 是当前阶段（扫描素材目录 / 向量回填），
         *     `summary` 是成功时的一句话摘要或失败时的异常串（截断 500 字，不含密钥），
         *     `result` 是成功时的计数 dict。**未知或已过期的 `task_id` 返回 200 + `PENDING`**
         *     （结果键的 TTL 是 1 小时：进度是临时的，素材本身以磁盘与数据库为准）。
         */
        get: operations["getMaterialTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出回收站
         * @description 递归扫 `<素材根>/_trash/`，返回里面的媒体文件（旁车跟着媒体走，不单独列出）。
         *     `_trash` 是回收站目录：扫描素材库时跳过它，所以「移进来」就等于出库。
         */
        get: operations["listTrashedMaterials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/trash/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 从回收站恢复
         * @description 把回收站里的一条（连同它的旁车）移回素材目录的**原相对路径**，并触发一次索引任务。
         *     **恢复等于重新入库**：新 uuid、重新打标；移入回收站时 `run_matches` 已被外键级联清理，
         *     历史候选不会回来。目标位置已有同名文件 → 409。
         */
        post: operations["restoreMaterial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/trash/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 真删回收站里的文件
         * @description 真删（不可恢复）：`paths` 给具体条目（连同旁车一起删），`all=true` 清空整个回收站；
         *     两者二选一必填，且 `confirm` 必须为 `true`（二次确认）。先整体校验再删，
         *     任何一条不在回收站里就 404，不做部分删除。
         */
        post: operations["purgeTrashedMaterials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取素材详情
         * @description 返回单个素材的完整索引信息（含爆点要素 `elements`）；非法或未知 id 一律 404。
         */
        get: operations["getMaterial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 修改素材元数据
         * @description 只接受 `title` / `tags` / `description`（白名单，其余字段一律 422 拒绝而不是静默忽略），
         *     且至少要给一个字段（否则 400）。写入落两处：先写同名旁车 `<素材文件名>.txt`
         *     （`标题: …` / `标签: a, b` / `描述: …`），再更新 `materials` 行——磁盘目录始终是
         *     唯一来源，重扫描会得到同一份事实。三个字段的值都没变时不写文件。
         *     标签会去空白、去 `#` 前缀并去重；去重后最多 14 个、单个标签最多 24 字（超出 400）。
         *     标题与描述按**单行**处理（换行折成空格），因为旁车是 `键: 值` 行格式。
         */
        patch: operations["updateMaterial"];
        trace?: never;
    };
    "/api/materials/{material_id}/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 把素材移进回收站
         * @description 把素材（连同它的 `.txt` / `.md` / `.json` 旁车）移到 `<素材根>/_trash/<原相对路径>`，
         *     并删掉索引行；回收站里已有同名时自动加 `-2` 序号，不覆盖。
         *     删行会让 `run_matches` 通过外键级联清理——**历史候选不再回来**（恢复 = 重新入库，
         *     新 uuid）。磁盘上文件已不在时仍然删行，响应里 `file_missing=true`。
         */
        post: operations["trashMaterial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyzeRequest: {
            /** @description 热点文本列表（话题句或链接文本均可） */
            hotspots: string[];
            /**
             * @description 每个热点返回的候选素材数量上限
             * @default 5
             */
            topk: number;
            /**
             * @description 预设线索快照（S6.7）：与 hotspots **一一对应、等长**；某一项为 null 表示该热点走正常拆解。
             *     非空的那一项会写进对应 hotspots 行的 clue 并**短路拆解节点**（用户确认/编辑过的标签原样生效，
             *     不重复付费）。不传时行为与不带该字段完全一致。
             */
            clues?: (components["schemas"]["HotspotClue"] | null)[];
        };
        AnalyzeAccepted: {
            /** @description 异步任务标识，用于轮询状态 */
            job_id: string;
            /**
             * Format: uuid
             * @description 运行记录标识，用于读取结果与报告
             */
            run_id: string;
        };
        ImageClueResult: {
            /** @description 模型给出的热点描述（≤ 500 字）；用户可编辑后作为 hotspots 提交 */
            raw_text: string;
            clue: components["schemas"]["HotspotClue"];
            /** @description 本次解析实际使用的 prompt 版本，如 {"image_hotspot_clue": 1} */
            prompt_versions: {
                [key: string]: number;
            };
        };
        JobStatus: {
            job_id: string;
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            /** @description 0–1 的完成比例 */
            progress: number;
            /** @description 当前所处步骤（拆解 / 检索 / 缺口 / 撰稿 / 报告） */
            current_step?: string;
            error?: components["schemas"]["ErrorResponse"] | null;
        };
        RunSummary: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Format: date-time */
            created_at: string;
            finished_at?: string | null;
            hotspot_count: number;
            /** @description 第一条热点的原文预览（超过 60 字截断加省略号） */
            hotspot_preview: string;
            topk: number;
            totals: components["schemas"]["RunTotals"];
            error?: string | null;
        };
        RunList: {
            items: components["schemas"]["RunSummary"][];
            total: number;
        };
        RunDetail: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Format: date-time */
            created_at: string;
            finished_at?: string | null;
            totals: components["schemas"]["RunTotals"];
            /** @description 本次运行各任务所用的 prompt 版本；键为 task_id，见 docs/contracts/prompt契约.md */
            prompt_versions: {
                [key: string]: number;
            };
            /** @description 本次运行中每个热点的分析结果 */
            hotspots: components["schemas"]["HotspotResult"][];
        };
        HotspotResult: {
            /** Format: uuid */
            hotspot_id: string;
            hotspot_raw: string;
            clue: components["schemas"]["HotspotClue"];
            coverage: components["schemas"]["Coverage"];
            candidates: components["schemas"]["MatchCandidate"][];
            draft?: components["schemas"]["Draft"] | null;
        };
        HotspotClue: {
            why_it_works: string[];
            mechanisms: {
                name: string;
                explain?: string;
            }[];
            elements: components["schemas"]["Element"][];
            match_keywords?: string[];
            audience?: {
                [key: string]: unknown;
            };
            borrow_angles?: string[];
            risk_notes?: string[];
        };
        Element: {
            /**
             * @description 爆点要素类型，口径见 docs/产品方案.md 第六节
             * @enum {string}
             */
            type: "ip" | "topic" | "scene" | "visual" | "emotion" | "sound" | "conflict" | "format" | "audience";
            value: string;
            /** @default 0.6 */
            weight: number;
            /** @default 0.7 */
            confidence: number;
            evidence?: string;
        };
        Coverage: {
            /** @description 被素材命中的线索要素权重占比 */
            ratio: number;
            covered: components["schemas"]["Element"][];
            gaps: components["schemas"]["Element"][];
        };
        MatchCandidate: {
            rank: number;
            /** Format: uuid */
            material_id: string;
            score: number;
            /** @description 该素材由哪些召回通道带回（literal / vector），用于解释排序来源 */
            recall_sources: ("literal" | "vector")[];
            hits: components["schemas"]["MatchHit"][];
            missing: components["schemas"]["Element"][];
            /** @description 为什么相关；不允许为空，系统不允许出现无理由候选 */
            reasons: string[];
            /** @description 建议怎么用（放开头 3 秒 / 当过程画面等） */
            usage: string;
            material: components["schemas"]["MaterialSummary"];
        };
        MatchHit: {
            /** @enum {string} */
            element_type: "ip" | "topic" | "scene" | "visual" | "emotion" | "sound" | "conflict" | "format" | "audience";
            clue_value: string;
            hit_value?: string;
            similarity?: number;
            contribution?: number;
        };
        MaterialSummary: {
            /** Format: uuid */
            id: string;
            path: string;
            /** @enum {string} */
            type: "video" | "image";
            title?: string;
            description?: string;
            tags?: string[];
            duration_s?: number;
            width?: number;
            height?: number;
            has_audio?: boolean;
            keyframes?: string[];
        };
        /** @description 素材库列表里的一条素材（磁盘目录是唯一来源，这里是索引副本）。 */
        MaterialItem: {
            /** Format: uuid */
            id: string;
            /** @description 素材绝对路径 */
            path: string;
            /** @enum {string} */
            type: "video" | "image";
            title: string;
            description: string;
            tags: string[];
            duration_s: number;
            width: number;
            height: number;
            has_audio: boolean;
            size_bytes: number;
            /** @enum {string} */
            source: "sidecar" | "vision" | "filename" | "legacy";
            keyframes: string[];
            /** Format: date-time */
            indexed_at: string;
            /** @description 相对素材根目录的父目录（正斜杠；直接放在根目录下时为空串），供前端显示主题 */
            dir: string;
        };
        /** @description 素材详情：列表项的全部字段 + 爆点要素。 */
        MaterialDetail: {
            /** Format: uuid */
            id: string;
            /** @description 素材绝对路径 */
            path: string;
            /** @enum {string} */
            type: "video" | "image";
            title: string;
            description: string;
            tags: string[];
            duration_s: number;
            width: number;
            height: number;
            has_audio: boolean;
            size_bytes: number;
            /** @enum {string} */
            source: "sidecar" | "vision" | "filename" | "legacy";
            keyframes: string[];
            /** Format: date-time */
            indexed_at: string;
            /** @description 相对素材根目录的父目录（正斜杠；直接放在根目录下时为空串），供前端显示主题 */
            dir: string;
            elements: components["schemas"]["Element"][];
        };
        /** @description 把一个素材移进回收站的结果。 */
        MaterialTrashResult: {
            /** Format: uuid */
            material_id: string;
            /** @description 移入前的相对路径（原样，不带序号） */
            path: string;
            /** @description 回收站里的相对路径（同名时带 `-2` 序号） */
            trashed_path: string;
            /** @description 磁盘上本来就没有这个文件（只删了索引行） */
            file_missing: boolean;
        };
        /** @description 回收站里的一条素材（旁车跟着媒体走，不单独列出）。 */
        TrashItem: {
            /** @description 相对 `_trash/` 的路径（正斜杠） */
            path: string;
            name: string;
            /** @enum {string} */
            type: "video" | "image";
            size_bytes: number;
            /** Format: date-time */
            mtime: string;
        };
        TrashList: {
            items: components["schemas"]["TrashItem"][];
            total: number;
        };
        /** @description 恢复请求：`path` 是回收站里的相对路径（正斜杠，越界一律 400）。 */
        TrashRestoreRequest: {
            path: string;
        };
        /**
         * @description 真删请求：`paths` 与 `all=true` 二选一必填，且 `confirm` 必须为 `true`（二次确认）。
         *     违反其中任一条都是 400。
         */
        TrashPurgeRequest: {
            paths?: string[];
            all?: boolean;
            confirm?: boolean;
        };
        TrashPurgeResult: {
            /** @description 真删掉的相对路径（含跟随媒体一起删的旁车） */
            deleted: string[];
            count: number;
        };
        /** @description 素材索引任务已受理；`task_id` 用于 `GET /api/materials/tasks/{task_id}`。 */
        MaterialTaskAccepted: {
            task_id: string;
        };
        /** @description 上传受理结果：文件已落盘，索引任务已投递。 */
        MaterialUploadAccepted: {
            task_id: string;
            /** @description 相对素材根目录的正斜杠路径（`<YYYY-MM>/名称.mp4`） */
            path: string;
            /** @description 实际落盘的文件名（同名时带 `-2` 序号） */
            name: string;
        };
        /** @description 素材索引任务的状态；未知或已过期的 task_id 也返回它（state=PENDING）。 */
        MaterialTask: {
            task_id: string;
            /** @enum {string} */
            state: "PENDING" | "STARTED" | "RETRY" | "SUCCESS" | "FAILURE";
            /** @description 当前阶段（扫描素材目录 / 向量回填） */
            step?: string | null;
            /** @description 成功时的一句话摘要，失败时的异常串（截断 500 字，不含密钥） */
            summary?: string | null;
            /** @description 成功时的计数 dict */
            result?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * @description `PATCH /api/materials/{material_id}` 请求体：只允许这三个字段（其余一律 422），
         *     且至少要给一个（否则 400）。未给的字段保持原值。
         */
        UpdateMaterialRequest: {
            title?: string;
            tags?: string[];
            description?: string;
        };
        MaterialList: {
            items: components["schemas"]["MaterialItem"][];
            total: number;
            limit: number;
            offset: number;
            /** @description 直接子目录及其素材数（受 q / type / source 影响，不受 dir 影响） */
            dirs: {
                path: string;
                count: number;
            }[];
        };
        Draft: {
            /** @description 标题备选，小红书标题上限 20 字 */
            titles: {
                text: string;
                style?: string;
            }[];
            cover_text?: string;
            first_3s?: string;
            body: string;
            tags: string[];
            shot_list?: string[];
            compliance_notes?: string[];
        };
        RunTotals: {
            llm_calls: number;
            prompt_tokens: number;
            completion_tokens: number;
            cost_cny: number;
            latency_ms: number;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "down";
            checks: {
                db: components["schemas"]["ComponentHealth"];
                redis: components["schemas"]["ComponentHealth"];
                llm: components["schemas"]["ComponentHealth"];
            };
        };
        ComponentHealth: {
            /** @enum {string} */
            status: "ok" | "down";
            detail?: string;
            latency_ms?: number;
        };
        ErrorResponse: {
            /** @enum {string} */
            code: "bad_request" | "validation_error" | "not_found" | "conflict" | "payload_too_large" | "dependency_unavailable" | "upstream_error" | "internal_error";
            message: string;
            detail?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description 请求格式或参数不合法 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 字段级校验失败 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 依赖不可用（不做降级，直接返回错误） */
        DependencyUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 请求体超过体积上限（上传超过 `[upload].max_size_gb`） */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 上游服务错误 */
        UpstreamError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
        RequestId: string;
    };
    requestBodies: never;
    headers: {
        /** @description 本次请求的标识 */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全部依赖可用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 存在不可用依赖 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    createAnalysis: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description 任务已接受 */
            202: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["ValidationError"];
            502: components["responses"]["UpstreamError"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    createImageClue: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 单张图片（jpg / png / webp，≤ 10 MB）
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 解析结果（未落库，供用户确认后随 clues 提交） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageClueResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["ValidationError"];
            502: components["responses"]["UpstreamError"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 历史运行列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description 运行尚未完成 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getRunReport: {
        parameters: {
            query?: {
                format?: "html" | "md";
            };
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 报告内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                    "text/markdown": string;
                };
            };
            404: components["responses"]["NotFound"];
            /** @description 运行尚未完成 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMaterialKeyframe: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path: {
                material_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 关键帧图片（JPEG） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    listMaterials: {
        parameters: {
            query?: {
                /** @description 关键词；匹配标题或任一标签（大小写不敏感的子串，去空白后为空即忽略） */
                q?: string;
                /** @description 素材类型 */
                type?: "video" | "image";
                /** @description 打标来源 */
                source?: "sidecar" | "vision" | "filename" | "legacy";
                /**
                 * @description 主题目录（相对素材根目录的路径，正斜杠）；空串表示只看直接放在根目录下的素材，
                 *     非空时按前缀匹配（含子目录）。不传 = 全部。
                 */
                dir?: string;
                limit?: number;
                offset?: number;
            };
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 素材列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialList"];
                };
            };
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    scanMaterials: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已受理索引任务 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialTaskAccepted"];
                };
            };
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    uploadMaterial: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 文件已落盘并受理索引任务 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialUploadAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getMaterialTask: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialTask"];
                };
            };
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    listTrashedMaterials: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 回收站内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashList"];
                };
            };
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    restoreMaterial: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrashRestoreRequest"];
            };
        };
        responses: {
            /** @description 已恢复并受理索引任务 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialTaskAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description 目标位置已有同名文件 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    purgeTrashedMaterials: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrashPurgeRequest"];
            };
        };
        responses: {
            /** @description 删除结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashPurgeResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getMaterial: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 素材详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    updateMaterial: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMaterialRequest"];
            };
        };
        responses: {
            /** @description 更新后的素材详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    trashMaterial: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 移入回收站的结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialTrashResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
}
