/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 逐项返回探测结果——数据库与 Redis 是**真实连接探测**；llm 项只校验**配置就绪性**（不发真实请求：会烧钱，也容易被网络抖动误判，与 probe.py 的口径一致）。任一不可用时整体状态为 down 并返回 503。
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交热点分析任务
         * @description 接受一个或多个热点文本，落库生成 hotspot 与 run 记录，投递异步任务后立即返回。
         *     同一请求内多个热点按顺序分别分析，互不影响。
         */
        post: operations["createAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询任务状态
         * @description 轮询任务进度；succeeded 后可凭 run_id 取结果，failed 时 error 字段给出失败原因。
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取运行结果
         * @description 返回该次运行的结构化结果：线索、候选素材、覆盖缺口与文稿。
         */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取报告
         * @description 返回渲染好的报告；html 为自带样式的单文件，md 为可直接复制的文本。
         */
        get: operations["getRunReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyzeRequest: {
            /** @description 热点文本列表（话题句或链接文本均可） */
            hotspots: string[];
            /**
             * @description 每个热点返回的候选素材数量上限
             * @default 5
             */
            topk: number;
        };
        AnalyzeAccepted: {
            /** @description 异步任务标识，用于轮询状态 */
            job_id: string;
            /**
             * Format: uuid
             * @description 运行记录标识，用于读取结果与报告
             */
            run_id: string;
        };
        JobStatus: {
            job_id: string;
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            /** @description 0–1 的完成比例 */
            progress: number;
            /** @description 当前所处步骤（拆解 / 检索 / 缺口 / 撰稿 / 报告） */
            current_step?: string;
            error?: components["schemas"]["ErrorResponse"] | null;
        };
        RunDetail: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Format: date-time */
            created_at: string;
            finished_at?: string | null;
            totals: components["schemas"]["RunTotals"];
            /** @description 本次运行各任务所用的 prompt 版本；键为 task_id，见 docs/contracts/prompt契约.md */
            prompt_versions: {
                [key: string]: number;
            };
            /** @description 本次运行中每个热点的分析结果 */
            hotspots: components["schemas"]["HotspotResult"][];
        };
        HotspotResult: {
            /** Format: uuid */
            hotspot_id: string;
            hotspot_raw: string;
            clue: components["schemas"]["HotspotClue"];
            coverage: components["schemas"]["Coverage"];
            candidates: components["schemas"]["MatchCandidate"][];
            draft?: components["schemas"]["Draft"] | null;
        };
        HotspotClue: {
            why_it_works: string[];
            mechanisms: {
                name: string;
                explain?: string;
            }[];
            elements: components["schemas"]["Element"][];
            match_keywords?: string[];
            audience?: {
                [key: string]: unknown;
            };
            borrow_angles?: string[];
            risk_notes?: string[];
        };
        Element: {
            /**
             * @description 爆点要素类型，口径见 docs/产品方案.md 第六节
             * @enum {string}
             */
            type: "ip" | "topic" | "scene" | "visual" | "emotion" | "sound" | "conflict" | "format" | "audience";
            value: string;
            /** @default 0.6 */
            weight: number;
            /** @default 0.7 */
            confidence: number;
            evidence?: string;
        };
        Coverage: {
            /** @description 被素材命中的线索要素权重占比 */
            ratio: number;
            covered: components["schemas"]["Element"][];
            gaps: components["schemas"]["Element"][];
        };
        MatchCandidate: {
            rank: number;
            /** Format: uuid */
            material_id: string;
            score: number;
            /** @description 该素材由哪些召回通道带回（literal / vector），用于解释排序来源 */
            recall_sources: ("literal" | "vector")[];
            hits: components["schemas"]["MatchHit"][];
            missing: components["schemas"]["Element"][];
            /** @description 为什么相关；不允许为空，系统不允许出现无理由候选 */
            reasons: string[];
            /** @description 建议怎么用（放开头 3 秒 / 当过程画面等） */
            usage: string;
            material: components["schemas"]["MaterialSummary"];
        };
        MatchHit: {
            /** @enum {string} */
            element_type: "ip" | "topic" | "scene" | "visual" | "emotion" | "sound" | "conflict" | "format" | "audience";
            clue_value: string;
            hit_value?: string;
            similarity?: number;
            contribution?: number;
        };
        MaterialSummary: {
            /** Format: uuid */
            id: string;
            path: string;
            /** @enum {string} */
            type: "video" | "image";
            title?: string;
            description?: string;
            tags?: string[];
            duration_s?: number;
            width?: number;
            height?: number;
            has_audio?: boolean;
            keyframes?: string[];
        };
        Draft: {
            /** @description 标题备选，小红书标题上限 20 字 */
            titles: {
                text: string;
                style?: string;
            }[];
            cover_text?: string;
            first_3s?: string;
            body: string;
            tags: string[];
            shot_list?: string[];
            compliance_notes?: string[];
        };
        RunTotals: {
            llm_calls: number;
            prompt_tokens: number;
            completion_tokens: number;
            cost_cny: number;
            latency_ms: number;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "down";
            checks: {
                db: components["schemas"]["ComponentHealth"];
                redis: components["schemas"]["ComponentHealth"];
                llm: components["schemas"]["ComponentHealth"];
            };
        };
        ComponentHealth: {
            /** @enum {string} */
            status: "ok" | "down";
            detail?: string;
            latency_ms?: number;
        };
        ErrorResponse: {
            /** @enum {string} */
            code: "bad_request" | "validation_error" | "not_found" | "conflict" | "dependency_unavailable" | "upstream_error" | "internal_error";
            message: string;
            detail?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description 请求格式或参数不合法 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 字段级校验失败 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 依赖不可用（不做降级，直接返回错误） */
        DependencyUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 上游服务错误 */
        UpstreamError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
        RequestId: string;
    };
    requestBodies: never;
    headers: {
        /** @description 本次请求的标识 */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全部依赖可用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 存在不可用依赖 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    createAnalysis: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description 任务已接受 */
            202: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["ValidationError"];
            502: components["responses"]["UpstreamError"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            404: components["responses"]["NotFound"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description 运行尚未完成 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getRunReport: {
        parameters: {
            query?: {
                format?: "html" | "md";
            };
            header?: {
                /** @description 客户端生成的请求标识；未提供时由服务端生成。用于贯穿日志、调用追踪与数据库记录。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 报告内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                    "text/markdown": string;
                };
            };
            404: components["responses"]["NotFound"];
            /** @description 运行尚未完成 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
