"""Alembic 初始迁移的集成用例（S2.3）。

验证 `upgrade head` 建齐 schema、`alembic check` 与 ORM 模型零差异、
`downgrade base` 可回滚且**保留扩展**（数据契约 §6），以及往返可重复执行。
容器 DSN 通过环境变量注入——`alembic/env.py` 统一从 AppConfig 取连接串。
"""

from __future__ import annotations

import asyncio
import os
import subprocess
import sys
import warnings
from pathlib import Path

import pytest
from alembic.config import Config
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

# 期望清单与 S2.2 共用同一份"契约 → 结构"映射，避免两处漂移
from test_db_schema import COLUMN_SPECS, EXPECTED_INDEXES

from alembic import command

pytestmark = pytest.mark.integration

PROJECT_ROOT = Path(__file__).resolve().parents[2]
REVISION = "0002"


@pytest.fixture
def alembic_config(postgres_dsn: str, monkeypatch: pytest.MonkeyPatch) -> Config:
    """把容器 DSN 注入环境变量（env.py 从 AppConfig 读），不碰 alembic.ini。"""
    monkeypatch.setenv("DATABASE_URL", postgres_dsn)
    return Config(str(PROJECT_ROOT / "alembic.ini"))


async def _tables(engine: AsyncEngine) -> set[str]:
    async with engine.connect() as conn:
        return set((await conn.execute(text(
            "SELECT tablename FROM pg_tables WHERE schemaname = 'public'"))).scalars())


async def _indexes(engine: AsyncEngine) -> set[str]:
    async with engine.connect() as conn:
        return set((await conn.execute(text(
            "SELECT indexname FROM pg_indexes WHERE schemaname = 'public'"))).scalars())


async def _extensions(engine: AsyncEngine) -> set[str]:
    async with engine.connect() as conn:
        return set((await conn.execute(text("SELECT extname FROM pg_extension"))).scalars())


async def _alembic(func, config: Config, *args: str) -> None:
    """在工作线程里执行 Alembic 命令。

    env.py 的在线模式内部用 `asyncio.run()`，直接在异步测试里调会撞事件循环，
    丢到线程里跑就没有"正在运行的 loop"了。
    """
    await asyncio.to_thread(func, config, *args)


async def _check(config: Config) -> None:
    """执行 `alembic check`：不抛差异异常即通过。

    trgm 表达式索引把算子类写在表达式里，Alembic 无法比较它、只会发一条 UserWarning
    并"假设相等"（`docs/contracts/数据契约.md` §4.1 的那条索引）。那是预期行为，
    这里只忽略这一条特定告警，其它差异仍然会让 `check` 抛错。
    """
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", message=".*operator clause.*", category=UserWarning)
        await _alembic(command.check, config)


class TestUpgrade:
    @pytest.mark.asyncio
    async def test_creates_tables_indexes_and_version(self, alembic_config: Config,
                                                      db_engine: AsyncEngine) -> None:
        await _alembic(command.upgrade, alembic_config, "head")
        assert set(COLUMN_SPECS) <= await _tables(db_engine)
        assert await _indexes(db_engine) >= EXPECTED_INDEXES
        async with db_engine.connect() as conn:
            version = (await conn.execute(text("SELECT version_num FROM alembic_version"))
                       ).scalar_one()
        assert version == REVISION

    @pytest.mark.asyncio
    async def test_check_reports_no_diff_against_models(self, alembic_config: Config,
                                                        db_engine: AsyncEngine) -> None:
        await _alembic(command.upgrade, alembic_config, "head")
        # 不抛 AutogenerateDiffsDetected 即"迁移与 ORM 模型零差异"
        await _check(alembic_config)


class TestDowngrade:
    @pytest.mark.asyncio
    async def test_downgrade_drops_tables_but_keeps_extensions(self, alembic_config: Config,
                                                               db_engine: AsyncEngine) -> None:
        await _alembic(command.upgrade, alembic_config, "head")
        await _alembic(command.downgrade, alembic_config, "base")
        assert not (set(COLUMN_SPECS) & await _tables(db_engine))
        assert {"vector", "pg_trgm"} <= await _extensions(db_engine)

    @pytest.mark.asyncio
    async def test_round_trip(self, alembic_config: Config, db_engine: AsyncEngine) -> None:
        await _alembic(command.upgrade, alembic_config, "head")
        await _alembic(command.downgrade, alembic_config, "base")
        await _alembic(command.upgrade, alembic_config, "head")
        assert set(COLUMN_SPECS) <= await _tables(db_engine)
        await _check(alembic_config)


class TestExtensionFallback:
    @pytest.mark.asyncio
    async def test_migration_recreates_missing_extensions(self, alembic_config: Config,
                                                          db_engine: AsyncEngine) -> None:
        # 此时库里还没有表，drop 扩展是安全的；验证迁移里 IF NOT EXISTS 那条兜底路径
        async with db_engine.begin() as conn:
            await conn.execute(text("DROP EXTENSION IF EXISTS vector"))
            await conn.execute(text("DROP EXTENSION IF EXISTS pg_trgm"))
        await _alembic(command.upgrade, alembic_config, "head")
        assert {"vector", "pg_trgm"} <= await _extensions(db_engine)
        assert set(COLUMN_SPECS) <= await _tables(db_engine)


class TestCliSmoke:
    @pytest.mark.asyncio
    async def test_documented_command_works(self, postgres_dsn: str,
                                            db_engine: AsyncEngine) -> None:
        """文档里写的 `uv run alembic upgrade head` 等价命令必须真能跑通。"""
        # 显式指定 UTF-8：子进程日志里有中文，而 Windows 的 locale 是 GBK
        env = {**os.environ, "DATABASE_URL": postgres_dsn, "PYTHONIOENCODING": "utf-8"}
        result = subprocess.run(
            [sys.executable, "-m", "alembic", "upgrade", "head"],
            cwd=str(PROJECT_ROOT), env=env, capture_output=True,
            text=True, encoding="utf-8", errors="replace")
        assert result.returncode == 0, result.stderr[-400:]
        assert set(COLUMN_SPECS) <= await _tables(db_engine)
